### ISSUE TITLE
After adding new device its location is not present on the map.

### ISSUE THREAD

**Issue by belussi** [Azure/pcs-remote-monitoring-webui#1012]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
After adding new device its location is not present on the map. I can see only predefined simulated devices location.

# Steps to reproduce 

1. Add new physical device with custom location - (45.5209, -122.684636) - Portland, OR
2. Try to find device on the map.

# Expected behavior 
Device location is being shown on the map.

# Current behavior 
No device present on the map.

# Known workarounds 
No workarounds.

# Possible solution 

# Context and Environment
* Operating System: Deployed from Azure Iot Suite, Chrom, Ubuntu 16.04, Mint 
* GitHub branch/tag: 1.0.0

# Screenshot 
![image](https://user-images.githubusercontent.com/1636110/40054250-83acf5f8-5844-11e8-8107-9f3fb0731e85.png)

![image](https://user-images.githubusercontent.com/1636110/40054382-f0b38950-5844-11e8-92d1-24a032bfdc9f.png)

**Comment by jillcary** [comment]
In order for the device to show on the map, the device needs to write its location in the form of latitude/longitude coordinates in the IoT Hub Device Twin.

Here is an example of what the simulated devices report:
![image](https://user-images.githubusercontent.com/3317135/40931943-b4d11c7a-67e1-11e8-94ed-2b8c915a7671.png)

In your device-side code, have the device report its location in the Device Twin Reported Properties.

**Comment by ppathan** [comment]
Fixed.
