### ISSUE TITLE
The webui crashs when the twin has a nested tags in reported

### ISSUE THREAD

**Issue by franji** [Azure/pcs-remote-monitoring-webui#1033]
# Type of issue 

- [x ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
The webui crashs when the twin has a nested tags in reported

# Steps to reproduce 
If the twin has nested tags in the reported 
Example:
"reported": {
   "telemetryConfig": {
"sendFrequency": "24h"
   }
}

If we enter the device section and click on some devices with nested tags, the portal crashes.

# Expected behavior 
The webui show the flayout with details about this device.

# Current behavior 
The webui crashs.

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: Windows 10
* GitHub branch/tag: ...

# Screenshot

**Comment by ppathan** [comment]
@isaac73 Can you look at this? It might be related to the work that you are doing with cache logic change and might be already fixed in your PR.

**Comment by isaac73** [comment]
@mechaffin looks like an issue in the dievices grid/flyout. Please take a look.
