### ISSUE TITLE
Verify the content of webui-config.js

### ISSUE THREAD

**Issue by guybartal** [Azure/pcs-remote-monitoring-webui#1044]
# Type of issue 

- [X ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

web app displays error when I browse to it.
I've tried to reboot website and the VM and it didn't solve the problem.

https://iot-mtc-il-rm-basic.azurewebsites.net/

...

# Steps to reproduce 

1. provision basic RM
2. send hundreds of messages
3. website crashes.

# Expected behavior 
working website
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ... win 10
* GitHub branch/tag: ... master (I guess, I've used https://www.azureiotsolutions.com to provision

# Screenshot 
![image](https://user-images.githubusercontent.com/3179107/42336796-6ea1b7cc-808d-11e8-9b96-ba9ebd532519.png)

**Comment by asdonald** [comment]
@frasparacio @guybartal Are you still facing this issue? I'm unable to repo. Please re-open if you still see this issue after completing a new deployment through azureiotsolutions.com

**Comment by Krummelz** [comment]
I created a new deployment, tried to replace the webui with a customized image, and this same error popped up when trying to browse the dashboard. I then stopped my custom container, and ran the old one again, but the error did not go away. Also tried restarting the vm. How does one resolve this? I don't want to re-deploy, because the whole point is that I need to be able to customise the UI.

**Comment by asdonald** [comment]
@isaac73 Customer re-opened with a comment. Can you please look into this with them?

**Comment by isaac73** [comment]
I personally haven't seen this message before. I tried to repro and did the following:

1. logged into VM
2. cd ./app
3. sudo nano docker-compose.yml
4. pointed the existing docker image of my webui to a new one
5. Ctrl+X
6. Y
7. cd ..
8. sudo docker stop $(sudo docker ps -a -q)
9. sudo docker rm $(sudo docker ps -a -q)
10. sudo docker rmi $(sudo docker images -q) -f
11. sudo /app/start.sh

The bug didn't repro.

@Krummelz Can you please try the above steps and let us know?

**Comment by sushilraje** [comment]
Hi, 
It seems that the error is related to the UI image. If you closely observe our docker-compose.yaml file, we mount a file webui-config.js (VM: under /app folder ) on the container at location (/app/build). It seems that this file is missing or corrupted in your container. Can you check if the file in the container?

**Comment by ekcworld** [comment]
Hi there,

I can recreate this issue as well. 
1. Create a .NET Cloud-Based RemoteMonitoring Solution following the steps below: 
https://docs.microsoft.com/en-us/azure/iot-accelerators/quickstart-remote-monitoring-deploy

2. After the solution is created/deployed, browse to the Remote Monitoring solution dashboard in your browser. You can load the dashboard page successfully.
e.g. https://my_remote_mornitoring_resource.azurewebsites.net/

3. Login to Azure portal, locate the VM of the Remote Monitoring solution in the Resource Groups

4. Stop the VM of the Remote Monitoring solution

5. Restart the VM of the remote Monitoring solution

6. Browse back to the dashboard page

7. The page can be no-longer accessible with an error:
my_remote_mornitoring_resource-vmaser.azurewebsites.net says
The dashboard configuration is missing.
Verify the content of webui-config.js

I would expect to load the dashboard page once the VM restarted. Any help would be appreciated.

Thanks,
-EK

**Comment by isaac-dasan** [comment]
@ekcworld After restarting the VM, did you do `docker ps -a` and find webUI running?

**Comment by ekcworld** [comment]
Hi Isaac, No. I am a newbie to Azure platform. :) Haven't used Docker.

**Comment by isaac-dasan** [comment]
> Hi Isaac, No. I am a newbie to Azure platform. :) Haven't used Docker. How can I find the webUI and start?

![image](https://user-images.githubusercontent.com/22013837/53590034-b95a5d00-3b45-11e9-89d6-026f16428fa0.png)

1. `sudo docker ps -a`
2. If don't see anything similar to the screen shot, do -> `sudo /app/start.sh`
3. If you see something like the screen shot, look at the row which says **azureiotpcs/pcs-remote-monitoring-webui:<tag>** and check the status column.

**Comment by ekcworld** [comment]
Thanks Isaac, I will try that out.

**Comment by ekcworld** [comment]
Hi Isaac, 

That fixed it. Thanks!

**Comment by pjjohnson** [comment]
You can set a Docker container restart policy https://docs.docker.com/config/containers/start-containers-automatically.  This might only cover up an existing problem. I've also gone the other path by creating an Azure Alert based on a log analytics query, and from that alert I can run a remote session to the Linux VM that restarts the container.

**Comment by gweisz** [comment]
I've textually just incurred into this issue, proof:

![image](https://user-images.githubusercontent.com/13660717/63544096-a758e600-c4fa-11e9-87c7-34a5377fd1ef.png)

Having read the above discussion I detected that the webui-config.js was mal-formed, e.g.

![image](https://user-images.githubusercontent.com/13660717/63544131-c788a500-c4fa-11e9-8dbb-374fcc44c572.png)

WA is:

(1) Generate the corrected file, use the proper appId
echo "var DeploymentConfig = { \
  authEnabled: true, \
  authType: 'aad', \
  aad : { \
    tenant: '', \
    appId: 'your appId', \
    instance: 'https://login.microsoftonline.com/' \
  } \
}" > /home/azureuser/webui-config.js

(2) Copy it into the container
docker cp /home/azureuser/webui-config.js app_webui_1:/app/build/webui-config.js

(3) Cleanup
rm /home/azureuser/webui-config.js

Please properly fix this issue as its still open

**Comment by colin-small** [comment]
How do you identify your appid? I tried copying a new config file to the path like you mentioned and it didn't seem to change the config file i see in the browser.. even after restarting everything.

**Comment by colin-small** [comment]
> I've textually just incurred into this issue, proof:
> 
> ![image](https://user-images.githubusercontent.com/13660717/63544096-a758e600-c4fa-11e9-87c7-34a5377fd1ef.png)
> 
> Having read the above discussion I detected that the webui-config.js was mal-formed, e.g.
> 
> ![image](https://user-images.githubusercontent.com/13660717/63544131-c788a500-c4fa-11e9-8dbb-374fcc44c572.png)
> 
> WA is:
> 
> (1) Generate the corrected file, use the proper appId
> echo "var DeploymentConfig = {
> authEnabled: true,
> authType: 'aad',
> aad : {
> tenant: '',
> appId: 'your appId',
> instance: 'https://login.microsoftonline.com/'
> }
> }" > /home/azureuser/webui-config.js
> 
> (2) Copy it into the container
> docker cp /home/azureuser/webui-config.js app_webui_1:/app/build/webui-config.js
> 
> (3) Cleanup
> rm /home/azureuser/webui-config.js
> 
> Please properly fix this issue as its still open

How do you identify your appid? I tried copying a new config file to the path like you mentioned and it didn't seem to change the config file i see in the browser.. even after restarting everything.
