### ISSUE TITLE
401 (Unauthorized)

### ISSUE THREAD

**Issue by acarum** [Azure/pcs-remote-monitoring-webui#1052]
# Type of issue 

- [ X] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
I'm not able to connect to backend resources ( such as \devidegroups) after a local deply of the webui
...

# Steps to reproduce 

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch/tag: ...

# Screenshot

**Comment by acarum** [comment]
Just to better explain my scenario; I have just deployed an Azure Iot Monitoring Solution on my Azure Portal using the web portal; then i have downloaded from github the source code for UI Portal and i'm trying to connect the backend, It should work, is it right?

**Comment by asdonald** [comment]
@acarum  Closing, please re-open if you are still having issues.
