### ISSUE TITLE
Configure WebUI to work with IoT Hub service

### ISSUE THREAD

**Issue by yaronA** [Azure/pcs-remote-monitoring-webui#1057]
Hi,

I have an IoT Hub running service over Azure cloud. How can I configure the pcs-remote-monitoring-webui running locally to connect directly to my IoT Hub over Azure cloud without using the IoT accelerator remote monitoring solution or docker?

Thanks.

**Comment by isaac73** [comment]
@yaronA  pcs-remote-monitoring-webui is not intended to connect to IOT Hub directly. You need all the supporting microservices that we have in remote-monitoring.

The main reason we developed solution accelerators remote monitoring solution is to create a wrapper around IOThub and various other Azure resources, so the customers don't have to create a solution of their own.
