### ISSUE TITLE
Dashboard Customization UI

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#107]
# Type of issue

- [ ] Bug
- [x ] New feature
- [ ] Improvement

# Description
Implement the dashboard customization UI.

Allows customization of: solution name, solution description, simulated device types, solution logo.

Also allows the creation of a "demo" experience.  This demo experience creates a default set of simulated device types/instances (using the simulation microservice) and rules (using the rules microservice).

**Comment by ppathan** [comment]
Tracked in TFS
