### ISSUE TITLE
NPM audit resulted in unresolved security vulnerabilities

### ISSUE THREAD

**Issue by sushilraje** [Azure/pcs-remote-monitoring-webui#1118]
Web ui has 91 security vulnerabilities,

Please do  "npm audit" to get a list of all.

Following are major issues,

1. install react-svg       high    npm install react-svg@6.0.20    Cross-Site Scripting    https://nodesecurity.io/advisories/648  react-svg       Y
2. update  hoek    moderate        npm update node-pre-gyp --depth 4       Prototype pollution     https://nodesecurity.io/advisories/566  node-sass-chokidar>chokidar>fsevents>node-pre-gyp>request>hawk>boom>hoek        N
3. install debug   low     npm install react-scripts@2.0.5 Regular Expression Denial of Service    https://nodesecurity.io/advisories/534  react-scripts>fsevents>node-pre-gyp>tar-pack>debug      Y
4. install randomatic      low     npm install node-sass-chokidar@1.3.4    Cryptographically Weak PRNG     https://nodesecurity.io/advisories/157  node-sass-chokidar>chokidar>anymatch>micromatch>braces>expand-range>fill-range>randomatic       Y

**Comment by asdonald** [comment]
@sushilraje to update with details and instructions for fix.

**Comment by sushilraje** [comment]
We have around 91 vulnerabilities,

If you do npm audit you will get a list of all of them

But majorly we have following,

1. install react-svg       high    npm install react-svg@6.0.20    Cross-Site Scripting    https://nodesecurity.io/advisories/648  react-svg       Y
2. update  hoek    moderate        npm update node-pre-gyp --depth 4       Prototype pollution     https://nodesecurity.io/advisories/566  node-sass-chokidar>chokidar>fsevents>node-pre-gyp>request>hawk>boom>hoek        N
3. install debug   low     npm install react-scripts@2.0.5 Regular Expression Denial of Service    https://nodesecurity.io/advisories/534  react-scripts>fsevents>node-pre-gyp>tar-pack>debug      Y
4. install randomatic      low     npm install node-sass-chokidar@1.3.4    Cryptographically Weak PRNG     https://nodesecurity.io/advisories/157  node-sass-chokidar>chokidar>anymatch>micromatch>braces>expand-range>fill-range>randomatic       Y

**Comment by mechaffin** [comment]
Package updates for npm audit vunerabilities is checked in already... https://github.com/Azure/pcs-remote-monitoring-webui/pull/1190.
