### ISSUE TITLE
Local debugging- Switching ON/OFF diagnostics in settings throws error

### ISSUE THREAD

**Issue by isaac73** [Azure/pcs-remote-monitoring-webui#1129]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

...

# Steps to reproduce 

1. click settings icon on right upper corner
2. click on/off for - Yes, share information with Microsoft
3. UI throws the below error

![image](https://user-images.githubusercontent.com/22013837/46772689-17c59280-ccae-11e8-8a06-5a342ec2db44.png)

**Comment by isaac73** [comment]
It looks like an auth issue. The error doesn't show up if you have admin access.

**Comment by mechaffin** [comment]
I do not see this error when the client and server. It does repro with a new client and a very old server. But if the server are of the same version, the issue does not repro.
