### ISSUE TITLE
When rule triggers, alerts shows GUID of rule rather than full text name, on page auto-refresh. Manual refresh (F5) fixed it.  

### ISSUE THREAD

**Issue by isaac73** [Azure/pcs-remote-monitoring-webui#1133]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
when rule triggers, alerts shows GUID of rule rather than full text name, on page auto-refresh. Manual refresh (F5) fixed it.

# Screenshot 
![rule bug](https://user-images.githubusercontent.com/22013837/47055075-79807380-d16a-11e8-8d77-256820ca7fb1.png)

**Comment by avneet723** [comment]
@mechaffin looks like it still repros. Could you please take a look? Thanks.
