### ISSUE TITLE
Search box size jagged

### ISSUE THREAD

**Issue by isaac73** [Azure/pcs-remote-monitoring-webui#1134]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Screenshot 
![searchbox bug](https://user-images.githubusercontent.com/22013837/47186418-5cbc7b00-d2e5-11e8-926a-b5db6fed9e5f.png)

**Comment by isaac73** [comment]
@Prasanna-Padmanabhan What branch was this found? any repo steps?

**Comment by Prasanna-Padmanabhan** [comment]
Sorry you got the wrong Prasanna :)

**Comment by VidNa** [comment]
@isaac73 I can repro it if you want to take a look at it. It repro'd on Edge browser, not in Chrome.

**Comment by isaac73** [comment]
@VidNa - @mechaffin was looking at this on Thursday. She was able to repro in Edge.

**Comment by mechaffin** [comment]
I am no longer seeing this behavior in Edge.
