### ISSUE TITLE
Production javascript code not bundled/minified

### ISSUE THREAD

**Issue by isaac73** [Azure/pcs-remote-monitoring-webui#1148]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Production javascript code not bundled/minified

**Comment by asdonald** [comment]
@mechaffin To investigate

**Comment by mechaffin** [comment]
The javascript is getting bundled. In the debug tools, it looks like its not because the source map is mapping things to look like the original files.
