### ISSUE TITLE
Big Blank Spot in Middle of Maintenance Page

### ISSUE THREAD

**Issue by asdonald** [Azure/pcs-remote-monitoring-webui#1154]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Description 

There's a blank spot in the middle of the maintenance page and I must scroll to the bottom to find the relevant information. 

# Steps to reproduce 

1. Create a rule that will trigger
2. Go to maintenance page
3. See 2 occurrences
4. Have to scroll down a lot to find the related information section

**Comment by mechaffin** [comment]
I don't see this.  Was it on a specific browser? Or perhaps an old/interim build version?
