### ISSUE TITLE
How to Refresh the Maintenance Page?

### ISSUE THREAD

**Issue by asdonald** [Azure/pcs-remote-monitoring-webui#1155]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Description 

Hard to know where to go to refresh the Maintenance Page. 

# Steps to reproduce 

1. Create a rule
2. Go to the maintenance page
3. See N alerts for that rule (along w/ other rules)
4. Click on the rule name for the detail view
5. Click on "Maintenance" in navigation
6. Still see N alerts for the rule
7. Have to click on Rules and then come back to Maintenance to see M alerts
8. Should have a more consistent way to get new data; not clear when things are cached

**Comment by mechaffin** [comment]
The refresh icon/button next to the Last Refreshed time should do this. Its the same on every page.
