### ISSUE TITLE
 Clicking sort on Rules column title (e.g. trigger) does not sort

### ISSUE THREAD

**Issue by asdonald** [Azure/pcs-remote-monitoring-webui#1160]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
To be specific: first click does work, but after 1 full loop (a->z, z->a, no sort), sorting doesn't work anymore
...

# Steps to reproduce 

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch/tag: ...

# Screenshot

**Comment by mechaffin** [comment]
The sorting appears to work for me on master. Can you give more info on when/where this was an issue?

**Comment by mechaffin** [comment]
The sorting works on most columns but not on others. Within the RulesGrid, rule name, description, severity, device group, and status all work fine.  I cannot tell if Notification works as the data is the same in all rows, but my suspicion is that its fine. Trigger, Count, and Last Trigger do not work.

For comparison, I checked the DevicesGrid as well. Those all appear to work fine.

Count and Last Trigger are loaded async (not in the same call that loads the rest of the grid).  The field value is not a simple value.  Its an object with multiple properties... which means the grid is unlikely to understand how to sort it.

Trigger is also an object containing all the conditions for the rule. 

I'll investigate use of custom comparator functions for these columns to enable sorting.
