### ISSUE TITLE
Custom configuration name text box prevents input of text with length less than 50

### ISSUE THREAD

**Issue by sushilraje** [Azure/pcs-remote-monitoring-webui#1184]
# Type of issue 

- [X] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
![image](https://user-images.githubusercontent.com/39531904/49135080-87adcd80-f29a-11e8-84e3-9f021e54be57.png)

...

# Steps to reproduce 

1. Add packages of custom configuration type with a name less than 50 chars

# Expected behavior 
Should allow the name of less than 50 chars

# Current behavior 
No

# Possible solution 
...

# Context and Environment Standard java deployment
* Operating System: ... Ubuntu
* GitHub branch/tag: ...

# Screenshot

**Comment by avneet723** [comment]
completed https://github.com/Azure/pcs-remote-monitoring-webui/pull/1175
