### ISSUE TITLE
"Access denied" after replacing webapp container image with a private image

### ISSUE THREAD

**Issue by isaac-dasan** [Azure/pcs-remote-monitoring-webui#1217]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

After replacing webapp container image with a private image and restarting the application, existing users get "Access Denied" message.

...

# Steps to reproduce 

1. Log in to VM
2. Open docker-compose.yaml file
3. replace web-ui container with a private one
4. start the app using the following steps
     * sudo docker stop $(sudo docker ps -a -q)
     * sudo docker rm $(sudo docker ps -a -q)
     * sudo docker rmi $(sudo docker images -q) -f
     * sudo /app/start.sh

# Expected behavior 

Existing users should retain their access

# Current behavior 

restart in "unsafe" mode

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch/tag: ...

# Screenshot

**Comment by isaac73** [comment]
I followed the same steps in another deployment but couldn't reproduce.

**Comment by isaac73** [comment]
![image](https://user-images.githubusercontent.com/22013837/52892381-c4c18780-3146-11e9-8dc3-81e037b80b28.png)

https://docs-sample.azurewebsites.net/

**Comment by isaac73** [comment]
![image](https://user-images.githubusercontent.com/22013837/52892396-e3278300-3146-11e9-89ca-effcf888991e.png)

Interestingly the services do not throw auth error

**Comment by Isaac-Johnson** [comment]
![image](https://user-images.githubusercontent.com/22013837/53115164-57bd4180-34fa-11e9-8f3e-fefb2305adde.png)

The call to auth service returns the above payload. So there must be some issue with auth service.
