### ISSUE TITLE
Unable to Edit Application Name

### ISSUE THREAD

**Issue by gauravagerwala** [Azure/pcs-remote-monitoring-webui#1224]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
The TextBox does not take more than 1 character inputs.
Applying the change does not change the application name either
...

# Steps to reproduce 
1. Click on Settings Button
2. Click on Edit under Name and Logo submenu
3. Try To Edit name

# Expected behavior 
Name changes
...

# Current behavior 
Changing the name in translations.json works
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch/tag: ...

# Screenshot

**Comment by ppathan** [comment]
Fixed.
