### ISSUE TITLE
Turning off simulation data doesn't work

### ISSUE THREAD

**Issue by ms-vincent** [Azure/pcs-remote-monitoring-webui#1228]
# Type of issue 

- [ x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

The slider button to turn off the simulated data doesn't work. 

# Steps to reproduce 

1. Create new Remote monitoring Solution Accelerator
2. Click settings gear.
3. try to turn off simulation data. Slider doesn't work, doesn't toggle off. The slider button highlights but it doesn't actually turn the data off. 

# Expected behavior 
slider moves to the left and turns off the simulated devices. 

![image](https://user-images.githubusercontent.com/16802088/53709553-e7ba8f80-3e06-11e9-907e-fbf0581afd45.png)

**Comment by codingbandit** [comment]
/static/js/components/shell/flyouts/settings/settings.js line 85 Cannot read property 'name' of undefined … target being passed into the onSimulationChange is undefined.
