### ISSUE TITLE
Telemetry chart not displaying report per time period drop down value

### ISSUE THREAD

**Issue by nareshshenishetty** [Azure/pcs-remote-monitoring-webui#1229]
# Type of issue 

- [X ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
From the Dashboard, select the last hour / lastday/last week/last month telemetry data to view on the telemetry panel chart. 

Telemetry chart always displays only last 15 to 20 min data, instead it should work as per the time-interval drop down.

# Steps to reproduce 

1. install pcs-remote-webui 2.2.0
2. open Dashboard
3. select time-interval drop down any 
4. verify the telemetry chart, will see only last 15 to 20 min irrespective of time drop down values.

# Expected behavior 

Telemetry chart should display the data per the time period drop down selected.

# Current behavior

**Comment by isaac-dasan** [comment]
@nareshshenishetty If the application is only deployed 20 mins ago, there wont be any telemetry before. This is an expected behavior. Can you double check?

**Comment by nareshshenishetty** [comment]
@isaac-dasan Verified. The application is running from quite long time. WebUI displaying last 20 min telemetry chart.

**Comment by nareshshenishetty** [comment]
@isaac-dasan still the issue exists Webui displaying only last 20min data irrespective of the time interval dropdown.

**Comment by ppathan** [comment]
@nareshshenishetty Did you try this on a new deployment or your existing deployment?

**Comment by nareshshenishetty** [comment]
Parvez, 
services --> Remote monitoring solution(dot net) running from quite long time. 
WebUI ( running Local, pointing to Azure deployed services running from quite long time)
tried both 1) on top of 2.2 took the latest commit 2) cloned latest master and tested.
Telemetry chart not showing the data per the time interval drop down selected.
