### ISSUE TITLE
Header does not show all the data

### ISSUE THREAD

**Issue by gauravagerwala** [Azure/pcs-remote-monitoring-webui#1232]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
After upgrading to 2.2.0 the header does not display correctly.

![image](https://user-images.githubusercontent.com/9166802/53843572-7eeb2880-3f68-11e9-8be4-504cf3073f1f.png)

# Expected behavior 
The header remains the same as the previous versions

**Comment by ppathan** [comment]
Hi @gauravagerwala We have recently changed the design to follow what you are seeing. Will close this issue as by design.
