### ISSUE TITLE
"View release notes" not underlined, they are links so it should be

### ISSUE THREAD

**Issue by ppathan** [Azure/pcs-remote-monitoring-webui#1238]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
"View release notes" not underlined, they are links so it should be

# Steps to reproduce 

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch/tag: ...

# Screenshot 
![image](https://user-images.githubusercontent.com/16170750/55114847-468ac600-50a0-11e9-936d-9238e6c58a03.png)

**Comment by elvinm** [comment]
Low priority UI bug. The link works but it needs to be styled. Removing bugbash label
