### ISSUE TITLE
I can not run npm install on my win10 in china mainland

### ISSUE THREAD

**Issue by pw007** [Azure/pcs-remote-monitoring-webui#1253]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

...

# Steps to reproduce 

1. run npm install
2. error: 
npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wdy_s\AppData\Roaming\npm-cache\_logs\2019-10-22T00_12_30_650Z-debug.log
3. npm --version: 6.4.1

Pls input some tips to help me move forward. Thx!
[2019-10-22T00_12_30_650Z-debug.log](https://github.com/Azure/pcs-remote-monitoring-webui/files/3753445/2019-10-22T00_12_30_650Z-debug.log)

...

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch/tag: ...

# Screenshot

**Comment by JonathanAsbury-ACS** [comment]
It's likely because you downloaded the source code as a zip and need to unblock it before extracting.  

<img width="273" alt="unblock_zip" src="https://user-images.githubusercontent.com/62960981/79808306-0ba2a280-8333-11ea-9a8a-229cdbc308e7.png">
