### ISSUE TITLE
Visualize rules associated to device on the Device Detail Flyout

### ISSUE THREAD

**Issue by CaitlinEsworthy** [Azure/pcs-remote-monitoring-webui#174]
# Type of issue

- [ ] Bug
- [x] New feature
- [x] Improvement

# Description

...Add component on the Device detail flyout (user can call this flyout from many locations on the web page). Component would likely be below the "Properties" section. Mockups should be located here: https://microsoft.sharepoint.com/teams/Azure_IoT/Shared%20Documents/PCS%20Team/Design/Design%20DRAFTS/Device%20Page/Designs%20-%20Redlines?csf=1 

# Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior

...

# Current behavior

...

# Known workarounds

...

# Possible solution

...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

# Code to reproduce the bug

```
using Xunit;

public class MyTest
{
    [Fact]
    public void TestToReproduceIssue()
    {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by ppathan** [comment]
done.
