### ISSUE TITLE
Dashboard breaks when resizing window

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#179]
# Type of issue
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
When resizing the browser window, the bottom part of the dashboard moves down out of the screen

# Steps to reproduce
1. Open the browser, not full screen
2. Go to the dashboard URL
3. Resize the browser window

# Expected behavior
The dashboard should resize accordingly to the window size

# Current behavior
Part of the dashboard moves in a wrong way and goes out of the viewport

# Known workarounds
Reloading the page after resizing the window

**Comment by ppathan** [comment]
done
