### ISSUE TITLE
Encapsulate all react component CSS

### ISSUE THREAD

**Issue by spryor** [Azure/pcs-remote-monitoring-webui#206]
# Type of issue
- [ ] Bug
- [ ] New feature
- [x] Improvement

# Description
All react component CSS needs to be encapsulated by a parent component class. Currently, many react components are polluting the global CSS namespace with class names. When the components are not encapsulated there is a much higher chance for class name collisions and overriding styles across components.

**Comment by ppathan** [comment]
@spryor What is the status of this issue?

**Comment by ppathan** [comment]
Tracked in TFS
