### ISSUE TITLE
Add Device details deep link to maintenance

### ISSUE THREAD

**Issue by hegate** [Azure/pcs-remote-monitoring-webui#227]
# Type of issue

- [ ] Bug
- [X] New feature
- [ ] Improvement

# Description
Missing from the current implemetation. To be done once we finish the dasbhboard.

...

# Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior

...

# Current behavior

...

# Known workarounds

...

# Possible solution

...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

# Code to reproduce the bug

```
using Xunit;

public class MyTest
{
    [Fact]
    public void TestToReproduceIssue()
    {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by maple10001** [comment]
Code changes checked in repo.
