### ISSUE TITLE
App should be resilient to invalid Ajax responses

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#260]
# Type of issue
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
When any of the background HTTP requests receive an error, which could be either plain text or XML, the application breaks with a fatal error.

All HTTP requests should go through one client, designed to be resilient to unexpected responses, logging an error, and maybe letting the user know that something went wrong (without flooding the user with error messages on the screen though).

Ideally there should be a "debugging mode", which might be just the browser console logs, where one can see:
* which request failed
* why they failed
* the impact of the failure, e.g. "unable to retrieve list of devices"

**Comment by ppathan** [comment]
Fixed.
