### ISSUE TITLE
Aggregated summary for Enable/Disable multiple rules

### ISSUE THREAD

**Issue by CaitlinEsworthy** [Azure/pcs-remote-monitoring-webui#298]
# Type of issue

- [ ] Bug
- [ ] New feature
- [X] Improvement

# Description

China team is currently working on this right now: in order to get a total number of devices effected in a multi-select of rules, we would have to filter out any overlap of device IDs.

**Comment by ppathan** [comment]
@darrenchuang I think this is done?
