### ISSUE TITLE
deviceGroupApiUrl not defined in config file

### ISSUE THREAD

**Issue by tiagoshibata** [Azure/pcs-remote-monitoring-webui#320]
# Type of issue
- [X] Bug
- [ ] New feature
- [ ] Improvement

# Description
The [`deviceGroupApiUrl` variable](https://github.com/Azure/pcs-remote-monitoring-webui/search?utf8=%E2%9C%93&q=deviceGroupApiUrl), used to request device groups, is used in the code but not defined in the config file.

Furthermore, [this line when adding a group](https://github.com/Azure/pcs-remote-monitoring-webui/blob/ebfff3794f21d6ffabf4e54b9e6148947f15821d/src/components/deviceGroupEditor/deviceGroupEditor.js#L79) resolves to `http://iotpcsdemo.azureedge.net/uiconfig/v1//api/v1/devicegroups/<new group name>`, which seems wrong to me (is the device group saved under `uiConfigApiUrl` or `deviceGroupApiUrl`? Should there be a double slash (`v1//api`) in the URL)?

# Steps to reproduce
Use device groups (e.g. create a group).

# Current behavior
Failure to connect to the endpoint (404).

# Possible solution
`deviceGroupApiUrl` should be defined in [config.js](https://github.com/Azure/pcs-remote-monitoring-webui/blob/master/src/common/config.js). Endpoint to create devices should be fixed.

# Context and Environment
* Operating System: Windows 10
* GitHub branch: master

**Comment by spryor** [comment]
The deviceList component has been removed. Closing.
