### ISSUE TITLE
Fonts for Bing map

### ISSUE THREAD

**Issue by swetha571** [Azure/pcs-remote-monitoring-webui#325]
# Type of issue

- [ ] Bug
- [ ] New feature
- [x] Improvement

# Description
This is an update from design to the currently used fonts. 

# Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior

...

# Current behavior

...

# Known workarounds

...

# Possible solution

...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

# Code to reproduce the bug

```
using Xunit;

public class MyTest
{
    [Fact]
    public void TestToReproduceIssue()
    {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by swetha571** [comment]
PR- https://github.com/Azure/pcs-remote-monitoring-webui/pull/640

**Comment by spryor** [comment]
Checked in
