### ISSUE TITLE
Tags aren't updated in the Device detail flyout when added to a device

### ISSUE THREAD

**Issue by corywink** [Azure/pcs-remote-monitoring-webui#329]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
When i change

# Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior

...

# Current behavior

...

# Known workarounds

...

# Possible solution

...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

# Code to reproduce the bug

```
using Xunit;

public class MyTest
{
    [Fact]
    public void TestToReproduceIssue()
    {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by maple10001** [comment]
dulp with #686
