### ISSUE TITLE
"user name unknown"

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#334]
# Type of issue
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
Even after signing in, on mouse over, the user icon shows "user name unknown"

![image001](https://user-images.githubusercontent.com/371009/30491031-b7195c46-99f0-11e7-956e-eeb67cac595e.png)

**Comment by ppathan** [comment]
Done.
