### ISSUE TITLE
Copy change: change word "Alarm" to Critical

### ISSUE THREAD

**Issue by CaitlinEsworthy** [Azure/pcs-remote-monitoring-webui#372]
# Type of issue

- [ ] Bug
- [ ] New feature
- [X] Improvement

# Description
the red word below the number should say "Critical" instead of "Alarm". This is copy error on the mocks.
![screen shot 2017-09-19 at 12 20 26 pm](https://user-images.githubusercontent.com/30060166/30611032-05cd36ae-9d35-11e7-82c4-dcb03b2a39d5.png)
...

**Comment by swetha571** [comment]
Duplicate issue: https://github.com/Azure/pcs-remote-monitoring-webui/issues/775
