### ISSUE TITLE
missing breadcrumb for maintenance details page

### ISSUE THREAD

**Issue by maple10001** [Azure/pcs-remote-monitoring-webui#389]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description

missing breadcrumb for maintenance details page
 - rule details
![image](https://user-images.githubusercontent.com/8744187/30668929-440a0b90-9e11-11e7-96c1-540b42b57662.png)
- job details
![image](https://user-images.githubusercontent.com/8744187/30668949-5bbd4bc6-9e11-11e7-86a8-64e4db1ea92d.png)

**Comment by spryor** [comment]
Initial breadcrumb added. Closing.
