### ISSUE TITLE
Telemetry radio buttons disappear when changing selection

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#417]
# Type of issue
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
Initial state after loading the dashboard:

![image](https://user-images.githubusercontent.com/371009/30715845-9cecede8-9ecc-11e7-9942-519330ebd9f9.png)

State after selecting "pressure", notice the missing radio buttons

![image](https://user-images.githubusercontent.com/371009/30715897-ce7c2a68-9ecc-11e7-8f3e-ead66d759ea0.png)

**Comment by maple10001** [comment]
closed with #413
