### ISSUE TITLE
app error while parsing telemetry data: "TypeError: Cannot read property 'Time' of undefined"

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#432]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
Not sure what the impact of this is, but it must be affecting the app somehow

![image](https://user-images.githubusercontent.com/371009/30758158-13fce5b4-9f86-11e7-86b6-35889880c3e1.png)

**Comment by maple10001** [comment]
Code changes checked in.
