### ISSUE TITLE
Clicking on Alarm or "..." from dashboard does not take you to the alarm details page

### ISSUE THREAD

**Issue by jillcary** [Azure/pcs-remote-monitoring-webui#438]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description

There is no deep link to the alarms page
![image](https://user-images.githubusercontent.com/3317135/30765189-40e3f0c8-9fa3-11e7-9f84-3aedace8797f.png)

# Steps to reproduce

1. open dashboard
1. click on alarm
1. nothing happens.

**Comment by timlaverty** [comment]
dup?

**Comment by spryor** [comment]
Fix merged, closing.

**Comment by spryor** [comment]
Reopening. There is an issue where navigation to the alarm details page fails if the user hasn't already navigated to maintenance page.
