### ISSUE TITLE
All text appearing in Times New Roman font

### ISSUE THREAD

**Issue by jillcary** [Azure/pcs-remote-monitoring-webui#450]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description

All of the fonts for Suite are showing as Times New Roman in  both Chrome and Edge with error

```
Error: "Failed to decode downloaded font: https://{endpoint}.azurewebsites.net/static/media/selawk.773ce5c5.ttf"
```
![image](https://user-images.githubusercontent.com/3317135/30787656-c297ca18-a142-11e7-9c9b-a1f3620059be.png)

# Steps to reproduce

1. Open dahsboard in browser

**Comment by ppathan** [comment]
Done.
