### ISSUE TITLE
Add IoT Hub connection string and device details after physical provisioning

### ISSUE THREAD

**Issue by hegate** [Azure/pcs-remote-monitoring-webui#468]
# Type of issue

- [ ] Bug
- [ ] New feature
- [X] Improvement

# Description
One a user finishes provisioning a new physical device, they should be able to see the connection string and device name so they can copy/paste that information without having to go to Ibiza.

**Comment by timlaverty** [comment]
I think this is a dup.

**Comment by ppathan** [comment]
Done.
