### ISSUE TITLE
Seeed data devices don't include Device type or firmware version

### ISSUE THREAD

**Issue by hegate** [Azure/pcs-remote-monitoring-webui#471]
# Type of issue

- [X] Bug
- [ ] New feature
- [ ] Improvement

# Description
![image](https://user-images.githubusercontent.com/12633955/30826063-f3175a76-a1e9-11e7-83eb-9d6e44eb4d25.png)

Please refer to specs in one note to update device properties.
...

**Comment by maple10001** [comment]
UI changes checked in for `Device Type`.
![image](https://user-images.githubusercontent.com/8744187/32067725-07ac1e9c-ba39-11e7-8cda-6c18a03a7197.png)
