### ISSUE TITLE
Seed simulated devices don't have the right tags

### ISSUE THREAD

**Issue by hegate** [Azure/pcs-remote-monitoring-webui#473]
# Type of issue

- [X] Bug
- [ ] New feature
- [ ] Improvement

# Description
When examining the simulated devices, I observe that the tags are not aligned with the spec. Examples:

Simulated engine 01

![image](https://user-images.githubusercontent.com/12633955/30826348-2af877f8-a1eb-11e7-9494-f1f47d94d3f6.png)

Simulated elevator 2

![image](https://user-images.githubusercontent.com/12633955/30826422-6b31bc1c-a1eb-11e7-920c-91a6b7e7fffb.png)

Simulated prototype 2
![image](https://user-images.githubusercontent.com/12633955/30826389-5254ab14-a1eb-11e7-9d9a-5665a8347786.png)

**Comment by swetha571** [comment]
Tested. Fixed the issue. 
![image](https://user-images.githubusercontent.com/16091688/35305739-56cfba22-004f-11e8-8799-63f82a59a373.png)
