### ISSUE TITLE
Fonts on map controls went back to Times New Roman

### ISSUE THREAD

**Issue by hegate** [Azure/pcs-remote-monitoring-webui#478]
# Type of issue

- [X] Bug
- [ ] New feature
- [ ] Improvement

# Description
I'm not sure if this is a regression?
![image](https://user-images.githubusercontent.com/12633955/30827144-ff605fb8-a1ed-11e7-9b61-f7bbbeb7fd22.png)

**Comment by ppathan** [comment]
Done.
