### ISSUE TITLE
Ag-grid column headers tooltip hover states

### ISSUE THREAD

**Issue by CaitlinEsworthy** [Azure/pcs-remote-monitoring-webui#481]
# Type of issue

- [ ] Bug
- [ ] New feature
- [X] Improvement

# Description
As discussed in sync on 9.22 (definitely GA and part of a larger project of identifying tooltip locations)

Hover state on the column titles reveals a tooltip explanation of what the column content is.

**Comment by Ram-SR** [comment]
I want the same. How can I add tooltip on hover on header cells?
