### ISSUE TITLE
After confirming jobs, there is no change of text

### ISSUE THREAD

**Issue by hegate** [Azure/pcs-remote-monitoring-webui#483]
# Type of issue

- [X] Bug
- [ ] New feature
- [ ] Improvement

# Description
When you confirm a job, for example in Schedule., we should get the confirmation so the user understands that the action happened.

![image](https://user-images.githubusercontent.com/12633955/30830228-1c458446-a1f8-11e7-93a5-1df2313894ce.png)

**Comment by hegate** [comment]
Perhaps just include a confirmation of "Job performed on X devices" after I click apply and get a response

**Comment by CaitlinEsworthy** [comment]
<img width="557" alt="screen shot 2017-11-30 at 10 18 33 am" src="https://user-images.githubusercontent.com/30060166/33448118-04c39f06-d5ba-11e7-8db3-1766a21d0f4f.png">
<img width="596" alt="screen shot 2017-11-30 at 10 17 59 am" src="https://user-images.githubusercontent.com/30060166/33448119-04d9b00c-d5ba-11e7-93c9-219ff077afd9.png">
<img width="457" alt="screen shot 2017-11-30 at 10 17 24 am" src="https://user-images.githubusercontent.com/30060166/33448120-04ebdbce-d5ba-11e7-9ac2-573e57914393.png">
