### ISSUE TITLE
Change text on rules enable/disable

### ISSUE THREAD

**Issue by hegate** [Azure/pcs-remote-monitoring-webui#500]
# Type of issue

- [X] Bug
- [ ] New feature
- [ ] Improvement

# Description
I believe the text for enabling and disabling the rules is not correct. It is confusing as it is, I don't know where I have to click to make it work..
![image](https://user-images.githubusercontent.com/12633955/30839810-e3ff5f40-a228-11e7-8a17-1813cd517701.png)

In that screenshot the rule is Enabled. The logic thing would be that the instead of saying "Enable selected rule", it should either say "Disable selected rule" to indicate action OR "Rule enabled" to indicate status, but "Enable selected rule is incorrect".

Also, when I select in the rules grid, enable/disable, I believe this was designed to be a toggle, not a button to take you to a details page, but we should check with Caitlin.

**Comment by CaitlinEsworthy** [comment]
@swetha571 and I discussed the changes to have the selection be more intuitive

Caitlin
