### ISSUE TITLE
Too many requests to /telemetry/v1/alarms

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#507]
# Type of issue

- [ ] Bug
- [ ] New feature
- [x] Improvement

# Description

The web UI keeps making these requests, every few seconds:

GET /telemetry/v1/alarms?devices=...&from=NOW-PT1H&to=NOW
GET /telemetry/v1/alarms?devices=...&from=NOW-PT2H&to=NOW-PT1H

I think that's too expensive and a waste of resources. Could the UI instead do:

1. onload GET /telemetry/v1/alarms?devices=...&from=NOW-PT2H&to=NOW
2. every few seconds GET /telemetry/v1/alarms?devices=...&from=NOW-PT1M&to=NOW

**Comment by ppathan** [comment]
Fixed.
