### ISSUE TITLE
multiple scrollbars when editing a filter

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#509]
# Type of issue
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
![image](https://user-images.githubusercontent.com/371009/30851151-9532c2ba-a25c-11e7-9978-2a17d9bcbb6a.png)

**Comment by swetha571** [comment]
Tested. I don't see this now.
![image](https://user-images.githubusercontent.com/16091688/35177810-cfb331d2-fd37-11e7-84cc-2f6cbbd06278.png)
