### ISSUE TITLE
Change "Int" to "Number" and "String" to "Text"

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#511]
# Type of issue
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
"Int" is actually incorrect because filters can be applied to real numbers. Anyway "Int" and "String" are not what people typically use outside of the software engineering world. Better labels would be "Number" and "Text".

![image](https://user-images.githubusercontent.com/371009/30851424-74d8bc58-a25d-11e7-80a0-8f61d04e6dae.png)

**Comment by swetha571** [comment]
Int to Number is already done. String to text in connected PR
