### ISSUE TITLE
Job Name cannot include spaces

### ISSUE THREAD

**Issue by dominicbetts** [Azure/pcs-remote-monitoring-webui#527]
# Type of issue

- [X] Bug
- [ ] New feature
- [ ] Improvement

# Description
A job name with spaces won't run:
![image](https://user-images.githubusercontent.com/1454644/30909169-1c9dc148-a378-11e7-8593-1407754af36d.png)

But this one will:
![image](https://user-images.githubusercontent.com/1454644/30909205-35dde5f2-a378-11e7-8edf-228f004f3077.png)

**Comment by swetha571** [comment]
Tested. Before the release week we have fixed this issue by 
1) adding the note below the jobName.
2) We also eliminate the space even if the user has given spaced job name.

![image](https://user-images.githubusercontent.com/16091688/35305584-abe96720-004e-11e8-8151-91185e8534cb.png)
