### ISSUE TITLE
Manage Filters - Delete and Edit icons should be horizontally aligned

### ISSUE THREAD

**Issue by jillcary** [Azure/pcs-remote-monitoring-webui#533]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description

The icons are showing on two lines instead of one:
![image](https://user-images.githubusercontent.com/3317135/30928811-7838c4dc-a371-11e7-8002-0513896498ea.png)

**Comment by swetha571** [comment]
PR #566
