### ISSUE TITLE
Side Pane UI on Dashboard overlaps when stacking in narrow window

### ISSUE THREAD

**Issue by jillcary** [Azure/pcs-remote-monitoring-webui#546]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description

![image](https://user-images.githubusercontent.com/3317135/30981268-bad93872-a438-11e7-876f-fd88ee60a93d.png)

**Comment by spryor** [comment]
Time range selection has been unified into the top context filters. Closing the issue.
