### ISSUE TITLE
Swap out round loading animation within the grid for the line animation.

### ISSUE THREAD

**Issue by CaitlinEsworthy** [Azure/pcs-remote-monitoring-webui#551]
# Type of issue

- [ ] Bug
- [ ] New feature
- [ ] Improvement

# Description
Swap out round loading animation within the grid for the line animation.
<img width="451" alt="screen shot 2017-09-28 at 10 26 15 am" src="https://user-images.githubusercontent.com/30060166/30988462-32294da2-a44f-11e7-8474-0755d5a2acd4.png">

**Comment by swetha571** [comment]
This is already implemented.
