### ISSUE TITLE
Telemetry chart x-axis values overlapping

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#555]
# Type of issue
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
![image](https://user-images.githubusercontent.com/371009/30996720-ac2a0d8a-a477-11e7-92bb-293f917d9a6c.png)

**Comment by timlaverty** [comment]
will be fixed by changing telemetry to show 15 minutes of data.

**Comment by maple10001** [comment]
close with #570
