### ISSUE TITLE
How do I read the Critical Alarm KPI?

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#556]
# Type of issue

- [ ] Bug
- [ ] New feature
- [x] Improvement

# Description

Should the title use singular or plural, "Alarm" or "Alarms" ?

I'm not sure how to interpret this box

![image](https://user-images.githubusercontent.com/371009/30996781-3392cd20-a478-11e7-9e28-c043c25ffd11.png)

probably we need more data to give an idea, or some more points of reference

**Comment by hegate** [comment]
I discussed this with @CaitlinEsworthy before. The idea is that this shows at least 4 data points per each time. For example: if it's last hour, it should show 4 15 min points. If it is 1 day, 4 6 hours points, and so on so forth. Does that make sense @timlaverty ?

**Comment by CaitlinEsworthy** [comment]
I think that Swetha was going to make the changes. @swetha571  do you have any questions or concerns?

**Comment by timlaverty** [comment]
@hegate This makes sense if the data exists; i.e. if there are minimum 4 critical alarms within the last hour.  When a solution is initially deployed, and shortly after, this data won't exist.  Do you want to show "No Data" until it has 4 points in the specified timeframe?  ...or start showing data @ 3 points?

IIUC this is showing the trend of critical alarms for the timeframe in question.  I wonder if a bar chart would better represent this (and wouldn't look odd w/ less data).  Thoughts?

**Comment by hegate** [comment]
@timlaverty I would vote for showing 3 points and then 4. That was the original intent @CaitlinEsworthy chime in if you disagree.

**Comment by timlaverty** [comment]
Swetha, please make the following changes:
1. When there are < 3 points of data for this control show "No Data".
2. When there are >= 3 points show the 3 points in a line graph.

**Comment by dluc** [comment]
nice to have: on mouse over "No Data" show a tooltip "this chart will show the KPI when there are at least 3 alarms"

**Comment by swetha571** [comment]
Updated Comps. 
![image](https://user-images.githubusercontent.com/16091688/31458392-cf8f9e0a-ae74-11e7-9363-b1a8d8c01955.png)
