### ISSUE TITLE
Table in the device flyout

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#558]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
![image](https://user-images.githubusercontent.com/371009/30996900-030b1f6c-a479-11e7-9705-79907f398ac6.png)

some issues I noticed:
* on load all the labels are truncated, e.g. "SEVER...", and I couldn't understand how to get the complete label. On mouse over perhaps I should see a tooltip with the complete value?
* I discovered that this is actually a table and I can resize the columns width. However, I found it by chance, it wasn't really clear it's a table. May be the contrast on my screen is hiding some details, I don't know
* I can resize a column to 0 pixels, maybe set a minimum size of 20-40 pixels?
* So it's a table, but it is empty, what's supposed to be in the table? Looks like the table is empty, but it doesn't tell the user that data is missing. Perhaps there should be a default value like "missing data" ?

**Comment by timlaverty** [comment]
tooltips portion of this is connected to https://github.com/Azure/pcs-remote-monitoring-webui/issues/574
