### ISSUE TITLE
Alignment of on New Rule flyout

### ISSUE THREAD

**Issue by CaitlinEsworthy** [Azure/pcs-remote-monitoring-webui#560]
# Type of issue

- [X] Bug
- [ ] New feature
- [ ] Improvement

# Description
the open input field does note align with the dropdown fields. The boxes should be on the same baseline.
![screen shot 2017-09-29 at 9 21 40 am](https://user-images.githubusercontent.com/30060166/31025807-dfe976a2-a4f8-11e7-88da-26c4f500b697.png)

When clicking into the field with the dropdown, the text jumps up  5 pixels. 
The carat icon should also rotate 180 degrees on open, and then back 180 degrees on close.
Increase dropdown height: it should automatically show more than 2 items (should show 8 before scrolling). Refer to the style guide section on Form Fields for spec.
![screen shot 2017-09-29 at 9 22 09 am](https://user-images.githubusercontent.com/30060166/31025810-e16bed02-a4f8-11e7-9e36-e8460c7ba082.png)

**Comment by spryor** [comment]
Fix checked in, closing. https://github.com/Azure/pcs-remote-monitoring-webui/pull/672
