### ISSUE TITLE
Update focus state in New Rule flyout

### ISSUE THREAD

**Issue by CaitlinEsworthy** [Azure/pcs-remote-monitoring-webui#561]
# Type of issue

- [ ] Bug
- [ ] New feature
- [X] Improvement

# Description
Override system default focus/pressed state of form elements and replace with more Microsoft aligned states (see style guide in OneNote).
![screen shot 2017-09-28 at 11 17 17 am](https://user-images.githubusercontent.com/30060166/31026689-2db32948-a4fc-11e7-9ba2-6b5b5257c2d6.png)
![screen shot 2017-09-29 at 9 52 17 am](https://user-images.githubusercontent.com/30060166/31026690-2db3b39a-a4fc-11e7-8875-7fc497e27782.png)

**Comment by spryor** [comment]
Fix checked in .
