### ISSUE TITLE
CRUD for tags doesn’t appear to work (but actually does)

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#568]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
Two problems: 
1. When we add or change tags and click the apply button there's no indicator that the tag(s) are being saved.  Apply should function as the other dialogs do (spinner) .
2.  The redux cache entry for the device isn't invalidated.  When the flyout is shown hubmanager should be requeried for just the device(s) edited if the cache is invalid.  To see the updated data right now you need to refresh the page.

**Comment by spryor** [comment]
Still in PR, reopening.

**Comment by spryor** [comment]
Fix checked in, closing.
