### ISSUE TITLE
Map doesn't show

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#569]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
The map doesn't show in some deployments.  Either a static map or a dynamic map should always be shown.

**Comment by swetha571** [comment]
I see the BingMap with latest deployment. @maple10001 and @spryor could you guys confirm if you see BingMap with latest deployment?

**Comment by timlaverty** [comment]
I see the following with a deployment from this morning:
![image](https://user-images.githubusercontent.com/5084013/31647048-7cd783c2-b2ba-11e7-8bb5-2b7eb3a7bf2c.png)

**Comment by timlaverty** [comment]
from deployment on 10/17:

![image](https://user-images.githubusercontent.com/5084013/31699366-7920337e-b377-11e7-9207-f10a45b04081.png)

**Comment by spryor** [comment]
Fix checked in, closing.
