### ISSUE TITLE
Flowing/Pause button - change text to "Paused"

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#571]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
The text for the pause state of the Flowing/Paused button should be "Paused".  Right now it is "Pause".

**Comment by CaitlinEsworthy** [comment]
This issue doesn't appear to be resolved correctly. Currently the ui looks like this when the telemetry is flowing:
![screen shot 2017-10-04 at 1 45 33 pm](https://user-images.githubusercontent.com/30060166/31198791-554f9a42-a90a-11e7-812e-8eb6126ee240.png)
And this is what it looks like when it is paused:
![screen shot 2017-10-04 at 1 43 06 pm](https://user-images.githubusercontent.com/30060166/31198805-619a6a16-a90a-11e7-938d-4c64edf8ceb2.png)

The words should be reversed, you should be able to "Pause" flowing data. 

This is what it should look like when data is flowing:
![screen shot 2017-10-04 at 2 03 53 pm](https://user-images.githubusercontent.com/30060166/31199731-306979ac-a90d-11e7-934d-f6615d74271b.png)

And this is what it should look like when it is paused:
![screen shot 2017-10-04 at 2 04 30 pm](https://user-images.githubusercontent.com/30060166/31199737-33096c94-a90d-11e7-8729-8e9971e539fe.png)

Icons are in the Sharepoint final icons folder.

@maple10001  please let me know if this isn't clear
