### ISSUE TITLE
Show progress indicator on all controls when updating

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#572]
# Type of issue

- [ ] Bug
- [x] New feature
- [x] Improvement

# Description
Show progress indicator on controls when updating data.  We will want Caitlin to help with the design.  For now please put this in the header.

**Comment by CaitlinEsworthy** [comment]
![refreshing data in tiles 3 57 09 pm](https://user-images.githubusercontent.com/30060166/31197403-d7f63500-a905-11e7-8b87-194befc283c1.png)
