### ISSUE TITLE
When there is no data for a control show a "No Data" in the middle of the control.

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#573]
# Type of issue

- [x ] Bug
- [ ] New feature
- [x ] Improvement

# Description
When there is no data for a control show a "No Data" in the middle of the control.  Please work with Caitlin on the design.

Do this for Tel chart, map, kpis, and alarm grid.

**Comment by CaitlinEsworthy** [comment]
Is there a link we can include to documentation that will help the user troubleshoot why there is no data ? Or is this in the event that they have requested, say, a filter that has no online devices, etc.?

**Comment by timlaverty** [comment]
@CaitlinEsworthy it could be a number of things including: 1) devices that are offline (as you said), 2) a service is down that queries the data, 3) a ruleset that is built that returns no data.

The struggle right now is the controls look "odd" when there is no data to present - we want it to be clear that there is no data to show vs. data to show vs. data is being refreshed.

**Comment by CaitlinEsworthy** [comment]
@swetha571 Please see these redlines and let me know if you have other questions
![no data styling](https://user-images.githubusercontent.com/30060166/31186119-a2b33992-a8e2-11e7-8d6c-3c77bcb9e124.png)

**Comment by spryor** [comment]
Fix checked in, closing.
