### ISSUE TITLE
Map, alarms grid, and KPIs use different timeframes to pull their data

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#575]
# Type of issue

- [x ] Bug
- [ ] New feature
- [x ] Improvement

# Description
Right now the chart, map, alarms grid, and KPIs show data in different time ranges.  map, alarms grid, and kpis all show alarm data.  Each control uses different timeframes to pull their data:

-      Chart == hardcoded to 15 minutes.
-	Map == hardcoded to 30 minutes.
-	Alarm Grid == user specified (default to last hour, can be last day/week/month)
-	KPIs == user specified (default to last hour, can be last day/week/month)
This is why map summary #s don’t match what’s in the alarm grid.

To fix this we will add a single time control the header, remove it from grid & kpis, and make each of the three controls adhere to it.  Telemetry we can leave alone as time scale is apparent from the x axis.

**Comment by CaitlinEsworthy** [comment]
Per design sync and chat with team: 
Include a time range filter in the dashboard that effects the map tile (will not change how many devices are online/offline/total); the Alarm tile; and the KPI tile
![dashboard mockup-global time range](https://user-images.githubusercontent.com/30060166/31153100-104ab924-a854-11e7-8a70-03b908aa03c5.png)
![dashboard mockup-global time range dropdown](https://user-images.githubusercontent.com/30060166/31153104-13077e7c-a854-11e7-96de-b42cfe6387a0.png)
