### ISSUE TITLE
Deep link to alarm detail from alarm grid

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#576]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
The ellipse in the alarm grid per row should deep link to the maintenance alarm detail page for that alarm.

**Comment by spryor** [comment]
Closing as a dup of https://github.com/Azure/pcs-remote-monitoring-webui/issues/438
