### ISSUE TITLE
When editing IsSimulated the type was changed to Boolean - should be left alone to string 	

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#591]
# Type of issue

- [ x] Bug
- [ ] New feature
- [ ] Improvement

# Description

When the IsSimulated tag was edited the type was changed to Boolean - it should be left alone as a string.

**Comment by spryor** [comment]
@timlaverty boolean was originally included in the design. My understanding is that the use of boolean was meant to help the user understand. We can, of course, change it to be string but I just want to double check that we are understanding correctly.
