### ISSUE TITLE
Need to show loading indicator when the grid is loading

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#593]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
When the grid is loading devices we need to show that it is loading.  Right now it's a blank screen, we need a loading indicator.

**Comment by CaitlinEsworthy** [comment]
Please show the following when a user has changed the device group filter and all the tiles are loading: 
![loading screen](https://user-images.githubusercontent.com/30060166/31152994-73b76e4a-a853-11e7-9d5d-d5fbf5121754.png)

Please show animated refreshing icons (mocked up below) with an animation style similar to [this](https://codepen.io/vkjgr/pen/nEvFA)
![refreshing data in tiles](https://user-images.githubusercontent.com/30060166/31152992-6f9a0db8-a853-11e7-993c-eb04733d91e0.png)

**Comment by timlaverty** [comment]
this should work the same for every control.

**Comment by spryor** [comment]
Fix checked in, closing.
