### ISSUE TITLE
No + for adding desired properties

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#595]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
The user should be able to add Desired properties, similar to how they add Tags.

**Comment by spryor** [comment]
Where is this happening?

**Comment by timlaverty** [comment]
![image](https://user-images.githubusercontent.com/5084013/31303367-51511e44-aac1-11e7-8ce3-84a438db610f.png)

**Comment by hegate** [comment]
Adding properties was indeed in scope as you mention Tim. Caitlin is updating the mocks now.
 
The way I am thinking about it is:
 
-	Simulated devices: you add a new property and that property turns into a reported property instantly. 
-	Physical devices: you add a new property and that property shows up as “Synching” until the client application has been updated to reflect the change (same as when you change property values).  Typically we wouldn’t recommend doing this as the cleanest way to do it. IMHO what makes more sense in a production environment is different versions of a device model that change with the client app. For example, when you move from 0.1 to 0.2 version, the twin is updated in the solution the first time the client app sends that new version and new properties show up in the model.
 
I do think the value is mostly for simulation, but it’s worth it.
