### ISSUE TITLE
Deep link to actual method details page, not the top level maint page

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#597]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
The deep link on the method job page should link to the maintenance details page for that actual job.

**Comment by spryor** [comment]
Related to the routing issue from https://github.com/Azure/pcs-remote-monitoring-webui/issues/438

**Comment by spryor** [comment]
Resolved in https://github.com/Azure/pcs-remote-monitoring-webui/pull/644
