### ISSUE TITLE
Deep link to actual method details page for alarm, not the top level maint page

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#599]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
For an alarm, we need to Deep link to actual alarm details page, not the top level maint page

**Comment by spryor** [comment]
Related to the routing issue from https://github.com/Azure/pcs-remote-monitoring-webui/issues/438

**Comment by spryor** [comment]
@timlaverty Is this the same issue as https://github.com/Azure/pcs-remote-monitoring-webui/issues/438? The alarms list in the dashboard?

**Comment by timlaverty** [comment]
yes, look like dups.

**Comment by spryor** [comment]
Closing as a duplicate
