### ISSUE TITLE
Rule Creation Flyout: Editing existing Rule doesn’t show FIELD or OPERATOR

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#604]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
Rule Creation Flyout: when editing an existing Rule the dialog doesn't show FIELD or OPERATOR - you need these to edit the rule.

**Comment by spryor** [comment]
Fix checked in. Closing.
