### ISSUE TITLE
Rule Creation Flyout: Flyout doesn’t show FIELD value when opened

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#605]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
Rule Creation Flyout: Flyout doesn’t show FIELD value when opened for creating a rule.

**Comment by swetha571** [comment]
This is fixed with issue 604. Fix PR- https://github.com/Azure/pcs-remote-monitoring-webui/pull/657.

**Comment by swetha571** [comment]
@spryor this is fixed with issue 604.

**Comment by spryor** [comment]
Completed, closing.
