### ISSUE TITLE
Rule creation: When editing an existing rule, going into Edit mode for the FIELD value that’s already used in a rule doesn’t show in the dropdown. 	

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#607]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
Rule creation: When editing an existing rule and going into Edit mode, the field value that’s already used in a rule doesn’t show in the dropdown.

**Comment by spryor** [comment]
Completed, closing.
