### ISSUE TITLE
Alarms: Ack, Open, Close buttons don’t work 	

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#608]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
Ack, Open, Close buttons don’t work for alarms.

**Comment by maple10001** [comment]
fix with #523

**Comment by timlaverty** [comment]
When a button is clicked show an hourglass (or something to show you clicked it)
	Data needs to be saved & refreshed in the grid.
	Grid, at least for the row(s) updated, needS to show that it's being updated.

**Comment by timlaverty** [comment]
I don't see the loading indicator or hourglass when these are clicked.
