### ISSUE TITLE
Alarm: Summary section heading Details: Total, Acknowledge, Severity need to be caps (like OPEN, CLOSED, and LAST EVENT are).

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#610]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
Alarm: Summary section heading Details: Total, Acknowledge, Severity need to be caps (like OPEN, CLOSED, and LAST EVENT are).

**Comment by spryor** [comment]
![alarmsummarycapsissues](https://user-images.githubusercontent.com/1734193/31298483-2b0258ec-aa9f-11e7-84b4-2a1e5ff4a10c.PNG)
