### ISSUE TITLE
web-ui should not stack up REST calls

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#613]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
Right now controls in the UI act on a timer, executing backend calls every X seconds.  They can continue to do this but should not execute calls if a previous call is pending.  Right now if the backend is unresponsive the calls will stack up and eventually crash the browser.

**Comment by spryor** [comment]
Fix checked in, closing.
