### ISSUE TITLE
Zero out numbers on reload of the page or on switching filters

### ISSUE THREAD

**Issue by CaitlinEsworthy** [Azure/pcs-remote-monitoring-webui#620]
# Type of issue

- [ ] Bug
- [ ] New feature
- [X] Improvement

# Description
To show more clearly that the new or correct data has been populated on the dash:
![zero out numbers](https://user-images.githubusercontent.com/30060166/31241425-ad4c6226-a9b8-11e7-9118-c1a9cafd91da.png)

**Comment by spryor** [comment]
The spinner is taking care of this issue.
