### ISSUE TITLE
Error modal design

### ISSUE THREAD

**Issue by CaitlinEsworthy** [Azure/pcs-remote-monitoring-webui#623]
# Type of issue

- [ ] Bug
- [X] New feature
- [ ] Improvement

# Description
As discussed in am sync:
Add modal over area of the UI that is experiencing the error, pulling useable information to the user. 
I think we may need to discuss this further as we implement but  please find a mockup of the Error Modal in the Styleguide on OneNote (Modal/tooltip tab).

<img width="1090" alt="screen shot 2017-10-05 at 11 51 51 am" src="https://user-images.githubusercontent.com/30060166/31247096-664a5570-a9c4-11e7-9a42-bde19d0af647.png">

**Comment by spryor** [comment]
Initial version checked in. Closing.
