### ISSUE TITLE
When there are no devices, we still see the telemetry flow on initial load.

### ISSUE THREAD

**Issue by swetha571** [Azure/pcs-remote-monitoring-webui#632]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
On initial load when there are no devices,  we still see the telemetry flow.
![image](https://user-images.githubusercontent.com/16091688/31350108-beb0bab0-acda-11e7-9f83-6c5d7ab2c5e2.png)

...

# Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior
When there are no devices on load, we should not show the telemetry flow.
...

# Current behavior

...

# Known workarounds

...

# Possible solution

...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

# Code to reproduce the bug

```
using Xunit;

public class MyTest
{
    [Fact]
    public void TestToReproduceIssue()
    {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by spryor** [comment]
Closing
