### ISSUE TITLE
Add Stop Simulation to UI

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#667]
# Type of issue

- [ ] Bug
- [ x] New feature
- [ x] Improvement

# Description
We need to add a “Stop Simulation” button to the UI.  We'd like to discuss options on where to add it: 1) every tab?, 2) just devices tab, ?

**Comment by timlaverty** [comment]
this will be added to the settings dialog.  Caitlin/Hector will design it.  Note this means the tooltip "Coming soon" won't show on the settings button.

**Comment by CaitlinEsworthy** [comment]
Just synched with Hector on the final copy to include:
"Start or stop the devices simulation data. Stopping the simulation data will minimize the cost of the solution. No telemetry will flow and rules will not be triggered for simulated devices."
See attached mocks here of the data flowing flow:
![settings](https://user-images.githubusercontent.com/30060166/31679021-bef5de88-b324-11e7-9486-268c94759bc7.png)
![settings 1](https://user-images.githubusercontent.com/30060166/31679028-c2beb094-b324-11e7-9fd6-d441ea29f96b.png)
![settings 2](https://user-images.githubusercontent.com/30060166/31679030-c4913360-b324-11e7-9345-ae0e4786a8db.png)

**Comment by spryor** [comment]
Complete.
