### ISSUE TITLE
There is no feedback when provisioning a new device

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#671]
# Type of issue

- [ ] Bug
- [ ] New feature
- [x] Improvement

# Description

When provisioning a new device and clicking the "Apply" button, the UI doesn't give any clue to the user, about the operation being complete or not, successful or not, leaving you wondering if you have to retry or what...

The UI should show something like "device successfully added" or "operation completed" with a green mark for example

![image](https://user-images.githubusercontent.com/371009/31635195-ca0623a0-b27a-11e7-8aa3-5b9a0144144d.png)

**Comment by spryor** [comment]
There is a currently open issue that should address this https://github.com/Azure/pcs-remote-monitoring-webui/issues/468 So this issue seems like a dup.

**Comment by dluc** [comment]
@spryor the issue is a little different. #468 is about showing the Connection String, which one needs to connect the device to ioT Hub.  The issue here is about having a visual clue that the user action was completed.

**Comment by CaitlinEsworthy** [comment]
Can someone assign this to me please?
