### ISSUE TITLE
Bad Request when hitting deep link URL directly

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#677]
# Type of issue

- [ ] Bug
- [ ] New feature
- [ ] Improvement

# Description
 https://<deployment>.azurewebsites.net/dashboard is placed into the browser you see "Bad Request".  

This happens with a number of other URIs too; e.g. https://<deployment>.azurewebsites.net/maintenance/rule/default_Elevator_Vibration_Stopped, https://<deployment>.azurewebsites.net/maintenance, https://<deployment>.azurewebsites.net/devices, ….

...

**Comment by spryor** [comment]
This may be an issue of an old image. The fix for this went in last week. After a quick check on the latest deployment we can't replicate the problem.

**Comment by timlaverty** [comment]
I think you’re right.  I couldn't deploy this with an image from today - I'll reopen if I can repro.

**Comment by timlaverty** [comment]
I still see this.  Repro:

1. Open site:  https://<mysite>.azurewebsites.net/dashboard
2. Open new tab in chrome.
3. Copy URL in:  https://<mysite>.azurewebsites.net/dashboard
4. See:

![image](https://user-images.githubusercontent.com/5084013/31900205-8e3653a6-b7d2-11e7-9315-900dd10fb0c3.png)

**Comment by dluc** [comment]
https://github.com/Azure/pcs-remote-monitoring-webui/pull/739 should address this issue

**Comment by spryor** [comment]
This issue has been resolved. Closing.
