### ISSUE TITLE
Time control does not pull the correct data

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#678]
# Type of issue

- [ ] Bug
- [ ] New feature
- [ ] Improvement

# Description

The time control does not pull the correct data: Alarms for an hour are < the number for for a day are < the number of alarms for a week.

# Steps to reproduce
Change the time control on the dashboard from 1 hour to a day to a week and watch the data refreshed.

**Comment by spryor** [comment]
The UI is simply showing what the service is returning. This seems like the service is returning something that doesn't make sense.

**Comment by timlaverty** [comment]
Jill, please partner with Stephen and figure out what queries are being executed & why the incorrect data is being returned.
