### ISSUE TITLE
Refresh button breakage

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#680]
# Type of issue

- [ x] Bug
- [ ] New feature
- [ ] Improvement

# Description
The refresh button and refreshed timestamp on each tab has problems:
- on dashboard it doesn't work at all.
- doesn't exist on devices and rules.
- on Maint it refreshes but is reentrant and doesn't update the last refreshed time.

We need to:
1. enable it on each tab.
2. should reload the page when clicked - loading indicator for controls should be shown.
3. should not be reentrant (clicking it multiple times in sequence should be blocked; e.g. protect from throttling).
4. should update the refreshed time to show the last time refreshed.
5. button should be centered with the text line it's on.

**Comment by spryor** [comment]
Checked in. Closing.
