### ISSUE TITLE
- Open occurrences isn’t accurate in Dashboard Alarms grid

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#681]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
- Open occurrences isn’t accurate in the Alarms grid (deep linking shows many alarms for the rule, the grid always shows just 1 occurrence)

![image](https://user-images.githubusercontent.com/5084013/31699247-ca6fa0e4-b376-11e7-8cd7-50e109cc7580.png)

**Comment by maple10001** [comment]
dep: https://github.com/Azure/device-telemetry-dotnet/issues/50

**Comment by spryor** [comment]
Closing as a dup https://github.com/Azure/device-telemetry-dotnet/issues/50. Not a UI issue.
