### ISSUE TITLE
When a job is completed it should show end time for the job

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#685]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
When a job is completed it should show end time for the job.  No end time is ever shown.

**Comment by spryor** [comment]
Pending https://github.com/Azure/azure-iot-sdk-csharp/issues/169 & https://github.com/Azure/azure-iot-sdk-csharp/pull/196
