### ISSUE TITLE
When Tag job completes, refresh the redux store

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#686]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
When a Tag update job completes we should update the redux local store for the devices affected by the job.

**Comment by spryor** [comment]
Fix checked in, closing.

**Comment by timlaverty** [comment]
I still see this happening:
1. Open Tag editor.
2. Use checkbox to select one device.
3. Click Tag button in action bar.  
4. Add a new Tag to the device.
5. Either: a) wait 30 seconds until you're sure the job has completed, or b) use the deep link and see the job complete.
6. Go back to the Devices page and soft-click the single device you added the Tag to. 
7. Look at the Tag list and see that the new tag you added is not there:
![image](https://user-images.githubusercontent.com/5084013/31910769-6daf0a44-b7f3-11e7-96aa-546b75c43eee.png)
8. Force a refresh of the redux cache (either by refreshing the browser or by changing the filter in some manner).  Note the new tag is now shown:
![image](https://user-images.githubusercontent.com/5084013/31910847-a176e4fa-b7f3-11e7-9d9d-36436855d415.png)
