### ISSUE TITLE
Time filter set to 1 week doesn't work

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#687]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
# Type of issue 

- [x ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
When setting the time filter to 1 week it causes 500 errors w/:

Message: "An error has occurred.",…}
ExceptionMessage
:
"The string 'P1W' is not a valid TimeSpan value."
ExceptionType
:
"System.FormatException"
Message
:
"An error has occurred."
StackTrace
:
[" at System.Xml.XmlConvert.ToTimeSpan(String s)",…]

![image](https://user-images.githubusercontent.com/5084013/31700391-ead9ddca-b37d-11e7-8735-802327195262.png)

**Comment by spryor** [comment]
Fix checked in, closing.
