### ISSUE TITLE
App not working in IE11, getting a blank page

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#699]
# Type of issue
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
When loading the app on IE11 (11.15.16299.0) I get a white empty page. The solution works fine in other browsers (Edge, Firefox, Chrome).

The console shows an error, which might be the root cause of the blank page: 
> Object doesn't support property or method 'endsWith'

likely the code at line 113:

![image](https://user-images.githubusercontent.com/371009/31845635-b8ff8bb0-b5b7-11e7-8f76-b7f9d0851c53.png)

"endsWith" is not supported by IE: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith

**Comment by mechaffin** [comment]
This looks like the @dluc  fix on 10/20/2017 fixed it... or a subsequent IE update did.  The UI came up just fine on IE Version 11.125.16299.0.
