### ISSUE TITLE
Remove "aadInstance.endsWith('{0}')" workaround

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#700]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
`auth.js` contains the following workaround needed by code in IoT Suite:

```
if (aadInstance && aadInstance.endsWith('{0}')) {
    aadInstance = aadInstance.substr(0, aadInstance.length - 3);
}
```

The code should be removed, including the temporary `endsWith` implementation added for IE.

**Comment by mechaffin** [comment]
Leaving as is.  The polyfill for endsWith is already in simulation repo. So this will be fixed during re-arch for GA.
