### ISSUE TITLE
UI broken in IE

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#702]
# Type of issue
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
See screenshot, telemetry is missing and alarms table is rendering poorly. Also, there are some javascript errors in the console.

![image](https://user-images.githubusercontent.com/371009/31846573-beec14d4-b5c2-11e7-8466-35d525ff1406.png)

**Comment by spryor** [comment]
This appears to be fixed.
