### ISSUE TITLE
Missing data in the telemetry chart

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#703]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
Notice how, after a page refresh, the same device "Simulated-truck-02-1" has more data points (red in the 1st char, blue in the 2nd chart):

![image](https://user-images.githubusercontent.com/371009/31847156-0d2ae3b0-b5cc-11e7-9f36-cc2891014532.png)
![image](https://user-images.githubusercontent.com/371009/31847157-11542726-b5cc-11e7-9cf9-f1d1c398736a.png)

**Comment by timlaverty** [comment]
https://github.com/Azure/pcs-remote-monitoring-webui/issues/286
