### ISSUE TITLE
When there are too many devices...

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#704]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description

Some API requests fail because the URL is too long
Telemetry chart is broken
Alarms don't show up

![image](https://user-images.githubusercontent.com/371009/31867997-aac1f28a-b74d-11e7-8fbf-823ef141599e.png)

**Comment by timlaverty** [comment]
What is the limit on devices?

**Comment by ppathan** [comment]
This is moved to post-Ti.
