### ISSUE TITLE
Updates to Static Map image

### ISSUE THREAD

**Issue by CaitlinEsworthy** [Azure/pcs-remote-monitoring-webui#706]
# Type of issue

- [ ] Bug
- [ ] New feature
- [X] Improvement

# Description
Update the Bing static with the new image, see mock-ups below:

- Get new image from Caitlin (dimensions TBD from @spryor )
- Make image responsive so that it re-centers on large screens
- Add a banner with the following text: "This solution has been configured with a static map. To learn more about adding an interactive map please visit our [FAQ](https://docs.microsoft.com/en-us/azure/iot-suite/iot-suite-faq)."
- Add link to the banner text: https://docs.microsoft.com/en-us/azure/iot-suite/iot-suite-faq 

![static image](https://user-images.githubusercontent.com/30060166/31903805-30ffe42a-b7de-11e7-8b2f-015790e2bc4f.png)

**Comment by spryor** [comment]
Image size: 1700px * 356px

**Comment by CaitlinEsworthy** [comment]
Thank you!!!! You are the best  ^_^
