### ISSUE TITLE
Add version and feature release link to UX

### ISSUE THREAD

**Issue by hegate** [Azure/pcs-remote-monitoring-webui#707]
# Type of issue

- [ ] Bug
- [X] New feature
- [ ] Improvement

# Description
In the setting tab, we should have an "About" section that indicates the RM version the users has displayed and a link to the GitHub release notes on that version. This is so that the user can understand which version they have deployed.

**Comment by CaitlinEsworthy** [comment]
See Mockup here for Settings (containing only the sections for Simulation flow and for Version, not the complete GA settings):

![settings 6](https://user-images.githubusercontent.com/30060166/31919721-46674d18-b819-11e7-8ca1-b4b3f7455901.png)

**Comment by hegate** [comment]
@CaitlinEsworthy lgtm please next time ping me on IM when you have it because I don't monitor all GitHub threads, thanks!

**Comment by spryor** [comment]
Complete.
