### ISSUE TITLE
Refresh should kick off loading indicators

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#713]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
1. On Dashboard - the Alarms grid isn't refreshed (or at minimum doesn't show the Loading indicator).
2. On Devices -
   a. controls aren't in the same action bar location - is this purposeful?
   b. Clicking refresh doesn't kick off load indicator.
3. On Rules - 
   a. controls aren't in the same action bar location - is this purposeful?
   b. Clicking refresh doesn't kick off load indicator.
4. Maintenance - 
   a. Alarms grid doesn't kick off load indicator.

**Comment by swetha571** [comment]
Yes. Second PR is coming up shortly. Intial PR is merged.
