### ISSUE TITLE
Updates to Simulation Data string

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#714]
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
Please change:
'''Start or stop the devices simulation data. Stopping the simulation data will minimize the cost of the solution. No telemetry will flow and rules will not be triggered for simulated devices.'''
to
'''Start or stop simulation of devices.  Stopping device simulation will minimize the cost of the solution; no simulated telemetry will be sent to your IoTHub and alarms will not be generated for simulated devices.'''

**Comment by spryor** [comment]
Fix checked in.
