### ISSUE TITLE
Refresh the grid after adding a device

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#720]
# Type of issue 

- [ x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
After adding a device we need to refresh the grid so the added device shows.  Right now you have to refresh the browser or change the filter back/forth to refresh the devices.  This is critical for physical devices added which are created in the hub immediately and should be shown.

**Comment by spryor** [comment]
Complete.
