### ISSUE TITLE
Add default state to controls in physical device creation

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#721]
# Type of issue 

- [x ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
When physical device creation is selected, by default check the radio buttons in the dialog.

Symmetric key and Auto generate keys should be checked:
![image](https://user-images.githubusercontent.com/5084013/32023977-d51da404-b98f-11e7-8579-fc7a12739ab2.png)

**Comment by spryor** [comment]
Complete.
