### ISSUE TITLE
Loading indicator broken on all tabs.

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#731]
# Type of issue 

- [x ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
The loading indicator should be shown when filter changes and when a page refreshes.  This was functional yesterday, likely was regressed with a merge last night.

We should *never* see a screen like this one.  The controls should be in one of three states: 1) have a "No data" label, 2) "have a loading indicator spinning, or 3) have data.

![image](https://user-images.githubusercontent.com/5084013/32069070-f40f79e8-ba3c-11e7-9342-fa59c96598de.png)

I don't see a loading indicator on any tab in the UI.

**Comment by maple10001** [comment]
From the UI, looks like an old deployment. At least the time selection should be globalized.
![image](https://user-images.githubusercontent.com/8744187/32069388-e1f16fc2-ba3d-11e7-8f0d-8c13b2279d69.png)

**Comment by timlaverty** [comment]
CNR
