### ISSUE TITLE
Custom Alarms/Rules not shown on dashboard

### ISSUE THREAD

**Issue by timlaverty** [Azure/pcs-remote-monitoring-webui#745]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Alarms for some custom rules don't shown in the dashboard alarms grid.  

Repro:
1. Add 4 chiller rules using pressure > 60 as the trigger.
2. Wait until the rules are triggered:
![image](https://user-images.githubusercontent.com/5084013/32124206-d23368ae-bb1b-11e7-9633-c537939cfae0.png)
3. Go to the dashboard and look @ the alarms grid, the alarms triggered from those rules are not in the grid.  There should be a page added to the control to allow the user to page through all alarms for any rule in the timeframe specified:
![image](https://user-images.githubusercontent.com/5084013/32124428-91621e50-bb1c-11e7-825f-a3b73deba8bf.png)

**Comment by spryor** [comment]
This issue has been resolved.
