### ISSUE TITLE
CLI deployment doesn't provide dynamic map

### ISSUE THREAD

**Issue by hegate** [Azure/pcs-remote-monitoring-webui#752]
# Type of issue 

- [X] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
I've tried deploying solution from CLI and didn't get a dynamic map. Over the same subscription using staging.azureiotsuite.com it works
...

# Steps to reproduce 

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch/tag: ...

# Screenshot

**Comment by timlaverty** [comment]
I see a dynamic map in my subscription:

**Comment by ppathan** [comment]
The only way you will see a dynamic map; if the subscription has less than 2 free Bingmap resources available. Closing this as by design.
