### ISSUE TITLE
White box appears in scroll bar corner

### ISSUE THREAD

**Issue by jillcary** [Azure/pcs-remote-monitoring-webui#763]
# Type of issue 
- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
When you make the solution window small, the scroll bar corner turns white.

![image](https://user-images.githubusercontent.com/3317135/32240045-7532d804-be29-11e7-8b30-44081e570a8a.png)

# Repro Steps
1. launch dashboard
2. make browser window smaller
3. notice white box appear

# Environment 
Chrome on Windows

**Comment by spryor** [comment]
Caused by missing `::-webkit-scrollbar-corner` definition.
