### ISSUE TITLE
When selecting all the alarms and ack/close them, it's not clear that I'm acting on all the pages

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#764]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Description 

In the maintenance page when I click the checkbox to select all the alarms, I'm expecting to select only the items in the current page, not all the pages. So when I click "close" or "acknowlege" I don't expect the action to modify the items in all the pages.

There are multiple ways to improve the UX, for instance asking the user "do you want to select the items in all the pages?" and when clicking "close" or "acknowledge" prompting for confirmation with a message like "This action will close N alarms, do you want to proceed?"

**Comment by CaitlinEsworthy** [comment]
This is an error @dluc in implementation. The action should only affect all the viewable items on the page. @spryor is there a problem with the ag-grid control in implementing this?
