### ISSUE TITLE
TMI in the maintenance page

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-remote-monitoring-webui#765]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Description 

The maintenance page has several elements and a lot of them are in bold white text, making it very crowded, and making it difficult to identify active/passive elements (buttons vs text). 
For instance it took me a while to find the "Close" and "Acknowledge" buttons, which are far from the list of alarms. Aside from the page content, these buttons should be closer to the list of alarms, while now there is a list of rules in between.

**Comment by CaitlinEsworthy** [comment]
Thanks for these comments @dluc will take them into account.

**Comment by ppathan** [comment]
There is a re-design need for maintenance page which will fix this issue.
