### ISSUE TITLE
Editing a rule on the rule detail page doesn't update the page

### ISSUE THREAD

**Issue by spryor** [Azure/pcs-remote-monitoring-webui#767]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description
1) Open a rule detail page
2) Soft select the rule (the first grid) 
3) Click "Edit" on the page and update the page name

The new name isn't reflected on the page, only the flyout. Also it isn't clear what the behavior is if the rule trigger is modified. Are the current alarms reevaluated or does changing the trigger effectively create a new rule?

**Comment by swetha571** [comment]
Tested. 
![image](https://user-images.githubusercontent.com/16091688/35177393-da506e1a-fd33-11e7-8b7e-b8c981cb2552.png)
