### ISSUE TITLE
Telemetry data doesn't appear on the alarm details page in IE

### ISSUE THREAD

**Issue by spryor** [Azure/pcs-remote-monitoring-webui#779]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description
The telemetry chart doesn't render in IE but it does in other browsers.

![capture](https://user-images.githubusercontent.com/1734193/32254645-5b31779a-be5f-11e7-8048-60a6b2593086.PNG)

**Comment by ppathan** [comment]
Done.
