### ISSUE TITLE
Ordering of Filters list in Manage Filters flyout

### ISSUE THREAD

**Issue by CaitlinEsworthy** [Azure/pcs-remote-monitoring-webui#781]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [X] Enhancement

# Description 
If users have extensive lists of Filters, it quickly becomes difficult to scan them to find the one you want to edit. I can provide designs as needed. Depending on what is possible to code:

- Ordering the list of Filters alphanumerically (if this is the method, would be good to add a flag on the item last created as it might become buried)

- Ordering them by time created (putting most recent at the top)

- Or both

**Comment by swetha571** [comment]
Its implemented.
