### ISSUE TITLE
Pop-up modal should only appear on FIRST load

### ISSUE THREAD

**Issue by CaitlinEsworthy** [Azure/pcs-remote-monitoring-webui#782]
# Type of issue 

- [X] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Pop-up modal should only appear on FIRST load, and not every hard refresh. Is this possible?
![screen shot 2017-11-01 at 11 18 20 am](https://user-images.githubusercontent.com/30060166/32294114-7c0a4502-bf02-11e7-80e8-7862a179407b.png)

**Comment by ppathan** [comment]
Fixed.
