### ISSUE TITLE
filter selection is not working on Rule & Action page 

### ISSUE THREAD

**Issue by maple10001** [Azure/pcs-remote-monitoring-webui#784]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
filter selection is not working on `Rule & Action` page 
...

# Steps to reproduce 

1. select `chiller` on `Dashboard`
2. goto `Rule & Action` page
3. select `All devices`

# Expected behavior 
filter should working

# Current behavior <!-- The actual behavior observed --
filter is not working

**Comment by swetha571** [comment]
Fix in https://github.com/Azure/pcs-remote-monitoring-webui/pull/800
