### ISSUE TITLE
Open Occurrences is not shown in the device detail flyout

### ISSUE THREAD

**Issue by darrenchuang** [Azure/pcs-remote-monitoring-webui#790]
# Type of issue 

- [X] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Open Occurrences is not shown in the device detail flyout
![image](https://user-images.githubusercontent.com/14215310/32308551-73805088-bfc1-11e7-860a-6d54ffea87e0.png)

# Steps to reproduce 

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
The Open Occurrences should be shown or this column should me removed?

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch/tag: ...

# Screenshot

**Comment by maple10001** [comment]
related to #786
