### ISSUE TITLE
User Settings

### ISSUE THREAD

**Issue by corywink** [Azure/pcs-remote-monitoring-webui#80]
# Type of issue

- [ ] Bug
- [ ] New feature
- [ ] Improvement

# Description
Need to define all the settings details, currently: 
- timezone

<outside of MVP?>
- simulation on\off
- modify project details
- user profile add/edit/delete

...

# Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior

...

# Current behavior

...

# Known workarounds

...

# Possible solution

...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

# Code to reproduce the bug

```
using Xunit;

public class MyTest
{
    [Fact]
    public void TestToReproduceIssue()
    {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by ppathan** [comment]
Tracked through TFS
