### ISSUE TITLE
Change text in Chrome

### ISSUE THREAD

**Issue by CaitlinEsworthy** [Azure/pcs-remote-monitoring-webui#801]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Replace app title with Microsoft brand adherent: "Microsoft Azure IoT Suite Remote Monitoring Preview"

**Comment by dluc** [comment]
if this is the browser title, i.e. the browser Tab title, I'd prefer a "Remote Monitoring - Microsoft Azure IoT Suite", so when the browser truncates it, the most contextual information remains visible.

**Comment by CaitlinEsworthy** [comment]
@dluc I will check in with the Content designer about it, but I think your logic makes sense
