### ISSUE TITLE
Change date stamp presentation to Microsoft brand m/d/17

### ISSUE THREAD

**Issue by CaitlinEsworthy** [Azure/pcs-remote-monitoring-webui#803]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [X] Enhancement

# Description 
Remove the "20" from "2017" and remove the "0" if the month or day has only one character. The presntation of date on the refresh control, the locations on all of the ag-grids and anywhere else in the application should look like:
m/d/17
For example:
5/5/17
**or**
10:22:04   6/12/17

**Comment by dluc** [comment]
@CaitlinEsworthy is the year abbreviation becoming a thing? #supernitpick: I'm seeing it being used in other places but I'm not sure I agree, considering the pain of reverting back to 4 digits every 90 yrs :-)

**Comment by CaitlinEsworthy** [comment]
@dluc I don't disagree with you. This issue is from a content review from the Content designer on the IoT Design team and she has loads of experience on different products here. I think there are pluses and minuses to both formats, but the ability to more quickly readable (with fewer digits) is pretty much the winner for me.

**Comment by dluc** [comment]
in terms of readability we should also consider localization.  For example, for European users 11/17/17 is less readable than 11/17/2017 because of the month-day Americanism.  Any chance we could format dates using the browser locale before truncating the year?
