### ISSUE TITLE
Dashboard : unit test for DeviceDetail, JsonViewer and DeviceGroupEditor

### ISSUE THREAD

**Issue by zhang-hua** [Azure/pcs-remote-monitoring-webui#82]
# Type of issue

- [ ] Bug
- [ ] New feature
- [x] Improvement

# Description

Add unit test for DeviceDetail component
Add unit test for JsonViewer component
Add unit test for DeviceGroupEditor component

**Comment by ppathan** [comment]
@spryor What is the eta for this?

**Comment by ppathan** [comment]
Tracked in TFS
