### ISSUE TITLE
Problem loading the ttf font file

### ISSUE THREAD

**Issue by franji** [Azure/pcs-remote-monitoring-webui#871]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
We are having problems with loading the ttf font file. 
When generating and loading the webui container the fonts are not loaded correctly. 
The following error appears :

Failed to decode downloaded font: /static/media/selawk.773ce5c5.ttf
OTS parsing error: incorrect entrySelector for table directory

We have checked the existing versions at https://hub.docker.com/r/azureiotpcs/pcs-remote-monitoring-webui/tags/ and they all have the same problem as of version 1.0.0-preview.2
The virtual machine where we are loading the containers is the one created for pcs-cli in azure by default.

# Expected behavior 
The texts should be displayed with the correct font.

# Current behavior
The texts are displayed with the wrong font.

# Context and Environment
* Operating System: Windows 10
* GitHub branch/tag: ...

# Screenshot 
![image](https://user-images.githubusercontent.com/2084775/35630128-d01a54f8-06a0-11e8-8e34-d635585700f1.png)

**Comment by ppathan** [comment]
Fixed.
