### ISSUE TITLE
Unhandled Rejection (SyntaxError): Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by remcoploeg** [Azure/pcs-remote-monitoring-webui#891]
# Type of issue 

- [X] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

Since this morning (three other developers tried on a new machine) when I get a clean PCS running, I get this error. Yesterday this was just working normally

Unhandled Rejection (SyntaxError): Unexpected token < in JSON at position 0
getJson
src/common/httpClient.js:89
  86 | 
  87 | function getJson(url, response) {
  88 |   if (response && typeof response !== 'undefined') {
> 89 |     return response.status !== 204 && response.status !== 401 && response.status !== 403
  90 |     ? response.json()
  91 |     : null;
  92 |   }

(anonymous function)
http://localhost:3000/static/js/bundle.js:51909:12
  51906 | 
  51907 | function get(url, options) {
  51908 |   return ajax(url).then(function (response) {
> 51909 |     return getJson(url, response);
        |            ^  51910 |   });
  51911 | }
  51912 | 

# Steps to reproduce 

1. npm install
2. npm start
3. open browser
4. get a startscreen for 1 or 2 seconds
5. then error occure

# Expected behavior 
Startpage with navigation

# Current behavior 
Error

# Known workarounds 
None

# Possible solution 
Don't know yet

# Context and Environment
* Operating System: Windows 10 and MacOS
* GitHub branch/tag: Latest Build

# Screenshot

**Comment by NathanNZ** [comment]
Check that REACT_APP_BASE_SERVICE_URL (set in the .env file) is pointing towards the correct location.

Out of box it seems to default to "/" and without nginx reverse proxying the API requests it will default to serving up the single page app. The "<" token is the start of the <!doctype html> tag.

**Comment by ppathan** [comment]
This is fixed.
